### ISSUE TITLE
Initial Successor product latched on subsequent searches

### ISSUE THREAD

**Issue by popeanthony** [ChrisHairstonBnR/Python-Successor-Finder#1]
If you perform a valid search, then perform a search for a product that does not have a valid successor, then the initial, valid successor product is shown.  

To reproduce:
search '8LSA35.E0030C1-0' - > Returns 8LSA35.E0030C1-3 (expected)
enter 'y' to start a new search
enter '3IF7E3.9' -> Returns 8LSA35.E0030C1-3 (bug)
![image](https://user-images.githubusercontent.com/107089319/223721448-2890aaa4-5680-467a-8107-912be94d69ed.png)

**Comment by ChrisHairstonBnR** [comment]
`materialOutput` variable was not resetting at the top of each iteration and therefore was carrying over into the next search. Issue should be fixed in next release.
