### ISSUE TITLE
Missing Obsolete Material - ACOPOSmulti

### ISSUE THREAD

**Issue by ClientRelationsUS** [ChrisHairstonBnR/Python-Successor-Finder#14]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/schwabk/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/schwabk/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Obsolete   Material | Successor
-- | --
8BVI0660HCS0.000-1 | 8BVI0660HCS0.008-1
8BVI0660HWS0.000-1 | 8BVI0660HWS0.008-1
8BVI0880HCS0.004-1 | 8BVI0880HCS0.008-1
8BVI0880HWS0.004-1 | 8BVI0880HWS0.008-1
8BVP0880HW00.004-1 | 8BVP0880HW00.008-1
8BVP0880HC00.004-1 | 8BVP0880HC00.008-1
8BVI1650HCS0.000-1 | 8BVI1650HCS0.004-1
8BVI1650HWS0.000-1 | 8BVI1650HWS0.004-1
8BVP1650HC00.000-1 | 8BVP1650HC00.004-1
8BVP1650HW00.000-1 | 8BVP1650HW00.004-1

</body>

</html>

**Comment by ChrisHairstonBnR** [comment]
Should be fixed with release of v0.90b. Please confirm at earliest convenience once released.

**Comment by brwjuan** [comment]
Confirmed the information is now being displayed.
